agent_framework: LangGraph
chunk_overlap: 50
chunk_size: 512
embedding_model_name: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2 #  can  be changes  any model embedding 
enabled_skills:
- pdf-reading
- docx
- zim creator
- create_zim_archive
- extract_pdf_text
- search_zim
llm_model_name: DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M #  cane be  use  any model  just  remove .gguf  and save in /models
llm_n_batch: 512
llm_n_ctx: 32768
llm_n_gpu_layers: 0
llm_verbose: true
models_dir: /home/USERNAME/Downloads/llamaZIM/models
skills_dir: /home/USERNAME/Downloads/llamaZIM/skills
vector_db_path: /home/USERNAME/Downloads/llamaZIM/vector_db
zim_archives_dir: /home/USERNAME/Downloads/llamaZIM/zim_archives
